# Generated by Django 4.1.1 on 2022-09-23 01:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "contact_no",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="PH"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PS", "Police Station"),
                            ("FS", "Fire Station"),
                            ("A", "Ambulance"),
                            ("LL", "Landlord"),
                        ],
                        max_length=30,
                        verbose_name="Emergency Number",
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Other Number",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
