# Generated by Django 4.1.1 on 2022-10-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency_contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PS", "Police Station"),
                    ("FS", "Fire Station"),
                    ("A", "Ambulance"),
                    ("LL", "Landlord"),
                ],
                max_length=30,
                null=True,
                verbose_name="Emergency Number",
            ),
        ),
    ]
