# Generated by Django 4.1.1 on 2022-10-19 11:21

from django.db import migrations, models
import django.db.models.deletion
import payments.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0004_room_rent_price_tenantroom_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("to", models.DateField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("up", "Unpaid"), ("pd", "Paid"), ("p", "Partial")],
                        default="up",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("R", "Rent"), ("Misc", "Miscellaneous")],
                        default="R",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_payments",
                        to="buildings.tenantroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        default=payments.utils.generate_transation_number,
                        editable=False,
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "payment_received",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("date_received", models.DateField()),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
