# Generated by Django 4.1.1 on 2022-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="to",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="until",
            new_name="start_date",
        ),
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
