# Generated by Django 4.1 on 2022-09-22 05:34

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="profiles/default/default.jpg",
                upload_to=users.utils.profile_directory_path,
                verbose_name="Profile Image",
            ),
        ),
    ]
