# Generated by Django 4.1.1 on 2022-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is verified or not.",
                verbose_name="Verfied",
            ),
        ),
    ]
