# Generated by Django 4.1.1 on 2022-09-23 01:45

from django.db import migrations, models
import django.db.models.deletion
import faqs.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("users", "0003_alter_userprofile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("question", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PI", "Payment Inquiry"),
                            ("RI", "ROOM INQUIRY"),
                            ("OTHER", "OTHER FAQs"),
                        ],
                        max_length=30,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Concern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "complaint_id",
                    models.CharField(
                        default=faqs.utils.generate_complaint_id,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("body", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Payment", "Payment Concern"),
                            ("Room", "Room Concern"),
                            ("Suggestion", "Suggestion"),
                            ("Other", "Other Concern"),
                        ],
                        max_length=50,
                        verbose_name="Concern Type",
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "complained_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.tenantroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("answer", models.CharField(max_length=500)),
                (
                    "answered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.landlord",
                    ),
                ),
                (
                    "complaint_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faqs.concern"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
