# Generated by Django 4.1.1 on 2022-10-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0003_concern_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concern",
            name="branch",
        ),
    ]
