# Generated by Django 4.1.1 on 2022-10-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_room_rent_price_tenantroom_start_date"),
        ("faqs", "0004_remove_concern_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concern",
            name="complained_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_concern",
                to="buildings.tenantroom",
            ),
        ),
    ]
