# Generated by Django 4.1.1 on 2022-10-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "Branches"},
        ),
    ]
