# Generated by Django 4.1.1 on 2022-10-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_alter_branch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenantroom",
                to="buildings.room",
            ),
        ),
    ]
