# Generated by Django 4.1.1 on 2022-10-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_alter_tenantroom_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="rent_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="If the type is 'Shared' make sure to enter the price per head.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="tenantroom",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
